CREATE MATERIALIZED VIEW mv_kursanci_filia
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT * FROM kursanci@dblinkFilia;

CREATE MATERIALIZED VIEW mv_wykladowcy_filia
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT * FROM wykladowcy@dblinkFilia;

CREATE MATERIALIZED VIEW mv_rodzaje_filia
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT * FROM rodzaje@dblinkFilia;

CREATE MATERIALIZED VIEW mv_kursy_filia
BUILD IMMEDIATE
REFRESH COMPLETE 
START WITH SYSDATE
NEXT SYSDATE + 1/24
AS
SELECT * FROM kursy@dblinkFilia;

EXECUTE DBMS_MVIEW.REFRESH('mv_kursanci_filia', 'C');
EXECUTE DBMS_MVIEW.REFRESH('mv_wykladowcy_filia', 'C');
EXECUTE DBMS_MVIEW.REFRESH('mv_rodzaje_filia', 'C');
EXECUTE DBMS_MVIEW.REFRESH('mv_kursy_filia', 'C');
